get http://localhost:4000/user-api/users

###
get http://localhost:4000/user-api/users/100

###
post http://localhost:4000/user-api/user
Content-Type: application/json

{
    "userId":200,
    "name":"manasa"
}

###
put http://localhost:4000/user-api/user
Content-Type: application/json

{
    "userId":100,
    "name":"suresh kumar"
}

###
delete http://localhost:4000/user-api/user/200

###
get http://localhost:4000/product-api/products